# Autogenerated with SMOP version 
# /usr/local/bin/smop quadricdata.m -o quadricdata.py
from __future__ import division
from runtime import *

def quadricdata(a,b,theta,d,nargout=1):
    lm_sx,lm_sy=meshgrid_(linspace_(- 0.5,0.5,d),linspace_(- 0.5,0.5,d),nargout=2)
    lm_sz=a.dot(lm_sx ** 2) + b.dot(lm_sy ** 2)
    ls_pts=0
    for x in arange_(1,size_(lm_sx,1)).reshape(-1):
        for y in arange_(1,size_(lm_sy,2)).reshape(-1):
            ls_pts=ls_pts + 1
            lm_nx[ls_pts]=lm_sx[x,y]
            lm_ny[ls_pts]=lm_sy[x,y]
            lm_nz[ls_pts]=lm_sz[x,y]
    R=matlabarray([[cos_(theta),- sin_(theta),0],[sin_(theta),cos_(theta),0],[0,0,1]])
    pts=matlabarray([[lm_nx],[lm_ny],[lm_nz]])
    pts=pts.T * R
    lm_nx=pts[:,1]
    lm_ny=pts[:,2]
    lm_nz=pts[:,3]
    x,y=meshgrid_(linspace_(- 1,1,d),linspace_(- 1,1,d),nargout=2)
    z=griddata_(lm_nx,lm_ny,lm_nz,x,y)
    for xi in arange_(1,size_(z,1)).reshape(-1):
        for yi in arange_(1,size_(z,2)).reshape(-1):
            if (isnan_(z[xi,yi])):
                z[xi,yi]=0
    return x,y,z
