# Autogenerated with SMOP version 
# /usr/local/bin/smop recreatesurf.m -o recreatesurf.py
from __future__ import division
from runtime import *

def recreatesurf(x,y,k1,k2,r1,r2,nargout=1):
    if (dot_(r1,r2) != 0):
        disp_('Principle directions not orthogonal!')
        return z
    H=(1 / 2) * (k1 + k2)
    K=k1 * k2
    alpha=(H - sqrt_(H ** 2 + K)) / 2
    gamma=(H + sqrt_(H ** 2 + K)) / 2
    theta=acos_(dot_(r1,[1,0]))
    a=alpha * cos_(theta) ** 2 + gamma * sin_(theta) ** 2
    b=(alpha - gamma) * cos_(theta) * sin_(theta)
    c=alpha * sin_(theta) ** 2 + gamma * cos_(theta) ** 2
    z=a * x ** 2 + b * x * y * c * y ** 2
    return z
